/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DeviceInfo {
  deviceId: string
  model: string
  deviceType: string
  ip: string
  nickname: string
  deviceOn: boolean
  mac?: string
  fwVer?: string
  hwVer?: string
  rssi?: number
  signalLevel?: number
  brightness?: number
  hue?: number
  saturation?: number
  colorTemp?: number
}
export interface DiscoveredDevice {
  deviceId: string
  model: string
  deviceType: string
  ip: string
  nickname: string
}
export declare class TapoPlug {
  turnOn(): Promise<void>
  turnOff(): Promise<void>
  getDeviceInfo(): Promise<DeviceInfo>
  refreshSession(): Promise<void>
}
export declare class TapoPlugEnergyMonitoring {
  turnOn(): Promise<void>
  turnOff(): Promise<void>
  getDeviceInfo(): Promise<DeviceInfo>
  refreshSession(): Promise<void>
}
export declare class TapoLight {
  turnOn(): Promise<void>
  turnOff(): Promise<void>
  setBrightness(brightness: number): Promise<void>
  getDeviceInfo(): Promise<DeviceInfo>
  refreshSession(): Promise<void>
}
export declare class TapoColorLight {
  turnOn(): Promise<void>
  turnOff(): Promise<void>
  setBrightness(brightness: number): Promise<void>
  setHueSaturation(hue: number, saturation: number): Promise<void>
  setColorTemperature(colorTemperature: number): Promise<void>
  getDeviceInfo(): Promise<DeviceInfo>
  refreshSession(): Promise<void>
}
export declare class TapoPowerStrip {
  getDeviceInfo(): Promise<DeviceInfo>
  refreshSession(): Promise<void>
}
export declare class TapoClient {
  constructor(email: string, password: string)
  /**
   * Discover all Tapo devices on the local network.
   * `broadcast_addr` defaults to "255.255.255.255" if not provided.
   * `timeout_secs` defaults to 5 if not provided.
   */
  discover(broadcastAddr?: string | undefined | null, timeoutSecs?: number | undefined | null): Promise<Array<DiscoveredDevice>>
  /** Connect to a plug device by IP address. Returns a TapoPlug handler. */
  plug(ip: string): Promise<TapoPlug>
  /** Connect to a plug with energy monitoring by IP address. */
  plugEnergyMonitoring(ip: string): Promise<TapoPlugEnergyMonitoring>
  /** Connect to a light bulb (L510/L520/L610) by IP address. */
  light(ip: string): Promise<TapoLight>
  /** Connect to a color light bulb (L530/L535/L630) by IP address. */
  colorLight(ip: string): Promise<TapoColorLight>
  /** Connect to a power strip (P300) by IP address. */
  powerStrip(ip: string): Promise<TapoPowerStrip>
}
